/**
 * Generates the icon data module from Google's Material Symbols (Rounded,
 * weight 300 — `@material-symbols/svg-300/rounded`, Apache-2.0), for exactly
 * the names in scripts/icons.manifest.mjs.
 *
 * The output is committed, so consumers never install the icon package — it is
 * a devDependency here, needed only to regenerate. scripts/build-icons.test.mjs
 * fails when the committed module drifts from the manifest.
 *
 * Adapted from quill-ds's build-icons.mjs (same source package, same
 * `{ viewBox, paths }` shape) without its lazy-loading tiers: a design system
 * ships the handful of icons it uses, not the whole library. Unlike quill's,
 * an unknown name is an ERROR, not a silent skip — a manifest entry that
 * renders nothing is exactly the quiet failure this engine refuses.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

import { ICON_NAMES } from './icons.manifest.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
export const ICON_SOURCE_DIR = join(root, 'node_modules/@material-symbols/svg-300/rounded')
// The registry item `icon` publishes this file next to components/ui/icon.tsx,
// so the component's relative import survives `shadcn add` unchanged.
export const ICONS_MODULE_PATH = join(root, 'components/ui/icons.generated.ts')

export function parseSvg(svg, name = 'icon') {
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1]
  if (!viewBox) throw new Error(`${name}: SVG has no viewBox`)
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1])
  if (paths.length === 0) throw new Error(`${name}: SVG has no <path d="…">`)
  return { viewBox, paths }
}

export function readIcon(name, dir = ICON_SOURCE_DIR) {
  const file = join(dir, `${name}.svg`)
  if (!existsSync(file)) {
    throw new Error(
      `'${name}' is not a Material Symbols (Rounded) icon — no ${name}.svg in ${dir}. ` +
        'Check the name at https://fonts.google.com/icons (names are snake_case).',
    )
  }
  return parseSvg(readFileSync(file, 'utf8'), name)
}

export function renderIconsModule(names = ICON_NAMES, dir = ICON_SOURCE_DIR) {
  const unique = [...new Set(names)].sort()
  const body = unique.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(readIcon(n, dir))},`).join('\n')
  return (
    '// GENERATED by scripts/build-icons.mjs from @material-symbols/svg-300 (Rounded, weight 300).\n' +
    '// Do not edit — add a name to scripts/icons.manifest.mjs and run `node scripts/build-icons.mjs`.\n' +
    'export interface IconData {\n  viewBox: string\n  paths: readonly string[]\n}\n\n' +
    `export const icons = {\n${body}\n} satisfies Record<string, IconData>\n\n` +
    'export type IconName = keyof typeof icons\n'
  )
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(ICONS_MODULE_PATH, renderIconsModule())
  console.log(`wrote ${ICONS_MODULE_PATH.slice(root.length + 1)} (${new Set(ICON_NAMES).size} icons)`)
}
