/**
 * Generates AGENTS.md — the compressed, always-loaded index an AI coding agent
 * reads before writing UI with Mantis.
 *
 * Why an index and not just docs: Vercel's agent eval (2026-01-27) found an
 * ~8KB index in AGENTS.md beat on-demand skills (100% vs 53–79%), because the
 * agent never has to decide to go look something up. So this file carries the
 * decisions (which component, which variant, which token) and points to the
 * per-component guides for the detail.
 *
 * Derived from components/ui (props, via the TypeScript checker), usage/*
 * (use-when, alternatives, rule ids), registry.json and the token module, so
 * it cannot drift. scripts/build-agents.test.mjs fails CI if the committed file
 * is stale. Run `node scripts/build-agents.mjs` after touching any of them.
 */
import { copyFileSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

import { tokens } from '../tokens/mantis.tokens.mjs'
import { ALL_USAGE } from '../usage/index.mjs'
import { readComponentApi } from './component-api.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
export const AGENTS_PATH = join(root, 'AGENTS.md')
export const CONSUMER_AGENTS_PATH = join(root, 'registry', 'MANTIS.md')
export const DESIGN_PUBLIC_PATH = join(root, 'public', 'design.md')

const code = (s) => `\`${s}\``

function propsLine(props, sharedWith, sameAsButton = () => false) {
  return Object.entries(props)
    .map(([component, list]) => {
      const shared = sharedWith(component, list)
      if (shared) return `${component}: same props as ${shared}`
      if (component !== 'Button' && list.length && list.every((p) => p.values && sameAsButton(p))) return `${component}: same props as Button`
      const parts = list
        // Icon names get their own section; repeating them per component is noise.
        .filter((p) => p.name !== 'name' || !p.values || p.values.length < 10)
        .map((p) => {
          if (!p.values) return `${p.name}: ${p.type}`
          // Buttons inside other primitives reuse Button's long value lists; point at them once.
          return component !== 'Button' && sameAsButton(p) ? `${p.name}=as Button` : `${p.name}=${p.values.join('|')}`
        })
      return parts.length ? `${component}(${parts.join(', ')})` : null
    })
    .filter(Boolean)
    .join(' · ')
}

// `consumer: true` renders MANTIS.md, the copy an app gets when it installs
// @mantis/base: the same index, with paths for an installed app and links to
// the hosted guides instead of files that only exist in this repo.
export function renderAgents({ t = tokens, api = readComponentApi(), usage = ALL_USAGE, consumer = false } = {}) {
  const L = []
  const p = (s = '') => L.push(s)
  const registry = JSON.parse(readFileSync(join(root, 'registry.json'), 'utf8'))
  const HOME = registry.homepage.replace(/\/$/, '')
  const pick = (repo, app) => (consumer ? app : repo)
  const guide = pick('`public/usage/<name>.md`', `\`${HOME}/usage/<name>.md\``)

  // A component whose props are identical to Button's (AlertDialogAction,
  // InputGroupButton…) says so instead of repeating the full list.
  const button = JSON.stringify(api.button?.props.Button ?? null)
  const sharedWith = (component, list) => (component !== 'Button' && JSON.stringify(list) === button ? 'Button' : null)
  const buttonValues = Object.fromEntries((api.button?.props.Button ?? []).filter((p) => p.values).map((p) => [p.name, [...p.values].sort().join('|')]))
  const sameAsButton = (prop) => buttonValues[prop.name] === [...prop.values].sort().join('|')

  p('# Mantis — agent guide')
  p()
  p(pick('<!-- Generated by scripts/build-agents.mjs from components/ui, usage/, registry.json and tokens/. Do not hand-edit; edit the sources and regenerate. -->', '<!-- Installed by @mantis/base. Reinstall the base item to update it rather than editing it. -->'))
  p()
  p('Mantis is a dark, cinematic design system (shadcn registry on Base UI, Tailwind v4). Build every screen from the components and token utilities below. **Prefer this file over your memory of shadcn:** variants, sizes and colors differ.')
  p()

  p('## Rules')
  p()
  p(pick('`npm run lint` enforces the ones marked ⛔; the rest are checked in review.', 'The Mantis repo fails its build on the ones marked ⛔; hold your code to the same bar.'))
  p()
  p("1. ⛔ **Colors come from tokens only.** No hex/rgb, no `bg-[#…]`, no Tailwind palette (`text-white`, `bg-zinc-900`). Use the utilities under *Tokens*. Motion and blur too: `duration-(--duration-normal)`, `backdrop-blur-glass`, never `duration-200` or `backdrop-blur-md`.")
  p('2. ⛔ **No arbitrary pixels** (`w-[13px]`) outside `components/ui`. Use the spacing scale (`w-105` = 420px) or a component size prop.')
  p("3. ⛔ **Base UI, not Radix.** Compose with `render`: `<DialogTrigger render={<Button variant=\"outline\" />}>Open</DialogTrigger>`. Never `asChild`. A link that looks like a button is a real `<a>` styled with `buttonVariants`: `<a href=\"/pricing\" className={buttonVariants({ variant: \"outline\" })}>` (Button with `render={<a>}` is announced as a button).")
  p("4. ⛔ **Icons:** `<Icon name=\"close\" />` from `@/components/ui/icon` only — never lucide-react. Names are listed under *Icons*.")
  p('5. **Lime (`brand`) marks the one main call to action on a screen:** generate, sign up, buy or upgrade a plan, the main marketing call to action, or the main action of a focused flow (upload, download, follow). Everyday confirm and save actions in forms, settings and dialogs (Save, Continue, Invite) use the white `default` button. One lime action and one filled button per view, card or dialog (a signed-out top bar\'s Sign up may repeat the page\'s own ask). No large lime areas besides the announcement bar and the marketing footer.')
  p('6. **Pink and blue are for offers, not buying:** `sale`, `badge-hot`, `badge-value` and `commerce-pink` mark sales, discounts and best-value tags. Plans are bought with the lime `brand` button, not `commerce-blue`.')
  p('7. **Dark only.** There is no light mode: never add a theme toggle or light-mode styles. Base styles already are the dark theme, so new code needs no `dark:` variants.')
  p(pick(
    '8. **Compose before you build, and ask before adding a primitive.** Patterns and screens go in `registry/` as blocks built from *Components*. If no primitive fits, stop and ask the owner before creating one in `components/ui`: a primitive changes the whole system. To add a pattern, follow the `mantis-build` skill (`.claude/skills/mantis-build/SKILL.md`).',
    '8. **Compose before you build.** Check *Blocks* for a ready-made pattern or page first (`npx shadcn@latest add @mantis/<name>`), then compose from *Components*. Do not restyle the installed files in `components/ui`; if nothing fits, ask the owner rather than forking a primitive.',
  ))
  p('9. **Content is your own.** Write real copy for the product (never lorem ipsum); images are `https://picsum.photos/seed/<slug>/<w>/<h>` with descriptive `alt`.')
  p(pick(
    '10. **Accessible by default.** Icon-only buttons get `aria-label`; every field gets a visible label; text meets 4.5:1 (the tokens already do — do not lower opacity on text). `data-contrast-exempt` is reserved for grey secondary text on stacked glass (owner decision, see CLAUDE.md); never use it anywhere else.',
    '10. **Accessible by default.** Icon-only buttons get `aria-label`; every field gets a visible label; text meets 4.5:1 (the tokens already do — do not lower opacity on text).',
  ))
  p()

  p('## Components')
  p()
  p(`Import from \`@/components/ui/<name>\`. Each entry: **name** exports · Mantis-specific props (\`=\` lists the allowed values) · what it is for · alternatives to weigh · rule ids. Full guide with do/don't: ${guide}.`)
  p()
  const byName = Object.fromEntries(usage.map((u) => [u.name, u]))
  for (const name of Object.keys(api).sort()) {
    const { exports, props } = api[name]
    const guide = byName[name]
    const parts = [`**${name}** ${exports.filter((e) => /^[A-Z]/.test(e)).join(', ')}`]
    const line = propsLine(props, sharedWith, sameAsButton)
    if (line) parts.push(line)
    if (guide) {
      parts.push(guide.summary)
      if (guide.alternatives.length) parts.push(`instead: ${guide.alternatives.map((a) => a.name).join(', ')}`)
      if (guide.rules.length) parts.push(`rules: ${guide.rules.map((r) => r.id).join(', ')}`)
    }
    p(`- ${parts.join(' · ')}`)
  }
  p()

  const blocks = registry.items.filter((i) => i.type === 'registry:block')
  if (blocks.length) {
    p('## Blocks')
    p()
    p(pick('Ready-made patterns in `registry/<name>.tsx`. Reuse or extend one before composing from scratch; full guide in `public/usage/<name>.md`.', `Ready-made patterns: \`npx shadcn@latest add @mantis/<name>\` installs one into \`components/<name>.tsx\`. Reuse or extend one before composing from scratch; full guide at ${guide}.`))
    p()
    // First clause of use_when only: enough to choose, and it keeps the index
    // small as the pattern library grows.
    const firstClause = (s) => {
      const clause = s.split(/;|, such as /)[0].trim()
      return clause.length <= 95 ? clause : clause.slice(0, clause.lastIndexOf(' ', 95)) + '…'
    }
    // Page templates get one compact line: their names say what they are, and
    // listing them like patterns would push the index past its size cap.
    const isTemplate = (b) => /^app-shell|-page$|-shell$/.test(b.name)
    for (const b of blocks.filter((b) => !isTemplate(b))) p(`- ${code(b.name)} (${(b.meta?.intent ?? []).join(', ')}) — ${firstClause(b.meta?.use_when ?? b.description)}`)
    const templates = blocks.filter(isTemplate)
    if (templates.length) {
      p()
      p(`**Page templates** (whole pages composed from the patterns above; start a new screen from the closest one): ${templates.map((b) => code(b.name)).join(', ')}.`)
    }
    p()
  }

  p('## Tokens')
  p()
  p('Every name below is a Tailwind color utility suffix: `bg-<name>`, `text-<name>`, `border-<name>`, `ring-<name>` (opacity works: `bg-brand/20`).')
  p()
  const keys = Object.keys(t.shadcn)
  const isGradient = (k) => /gradient/.test(t.shadcn[k])
  const fills = keys.filter((k) => !isGradient(k) && !k.endsWith('-foreground') && keys.includes(`${k}-foreground`))
  const standalone = keys.filter((k) => !isGradient(k) && !k.endsWith('-foreground') && !keys.includes(`${k}-foreground`))
  const gradients = keys.filter(isGradient)
  p(`- **Fill + text pairs** (put \`text-<name>-foreground\` on \`bg-<name>\`): ${fills.map(code).join(', ')}`)
  p(`- **Single roles:** ${standalone.map(code).join(', ')}`)
  p(`- **Gradients** (use as \`bg-[image:var(--<name>)]\`): ${gradients.map(code).join(', ')}`)
  p('- **Meaning:** `background` page · `card`/`soft` raised panels · `glass` translucent controls (`glass-hover` on hover) · `field` inputs · `chip` composer chips · `dialog` modals · `overlay` scrims · `muted-foreground` secondary text · `brand` lime · `primary` white · `separator`/`divider` hairlines · `tile-*` icon-tile colors.')
  p(`- **Text styles:** ${Object.keys(t.textStyles ?? {}).map((k) => code(`text-${k}`)).join(', ')} (size, line height, weight and tracking in one class), plus \`text-2xs\`…\`text-6xl\`. Fonts: ${Object.keys(t.font).map((k) => code(`font-${k}`)).join(', ')}.`)
  p(`- **Radius:** ${Object.keys(t.radius).map((k) => code(`rounded-${k}`)).join(', ')}, \`rounded-full\`. Controls use \`rounded-control\`.`)
  p(`- **Shadows:** ${Object.keys(t.shadow).map((k) => code(`shadow-${k}`)).join(', ')}.`)
  if (t.animate) p(`- **Motion:** ${Object.keys(t.animate).map((k) => code(`animate-${k}`)).join(', ')}. Interactions dim on hover (\`hover:brightness-80\`) and press (\`active:brightness-60\`) over 200ms.`)
  p()

  const iconNames = api.icon?.props.Icon?.find((prop) => prop.name === 'name')?.values ?? []
  if (iconNames.length) {
    p('## Icons')
    p()
    // Names live in the manifest; listing all of them here costs more index
    // space than it saves lookups once the set passes a few dozen.
    const common = ['add', 'close', 'check', 'search', 'more_vert', 'download', 'share', 'settings'].filter((n) => iconNames.includes(n)).map(code).join(', ')
    p(pick(
      `${iconNames.length} icons are bundled; their names are in \`scripts/icons.manifest.mjs\` (common: ${common}). Any other Material Symbols Rounded name works after adding it to that file and running \`node scripts/build-icons.mjs\`.`,
      `${iconNames.length} icons are bundled; their names are the keys of \`components/ui/icons.generated.ts\` (common: ${common}). \`IconName\` is a typed union, so an unknown name fails the typecheck. A missing icon needs a new Mantis release; ask the owner.`,
    ))
    p()
  }

  p('## Look things up')
  p()
  if (consumer) {
    p(`- Per-component do/don't, accessibility and tokens: ${guide}.`)
    p(`- Live examples of every component, pattern and page: <${HOME}/storybook/>`)
    p("- Registry search and install: the shadcn MCP server (`npx shadcn@latest mcp init`), namespace `@mantis`.")
    p(`- Visual intent and composition recipes: <${HOME}/design.md>. Full catalog: <${HOME}/llms.txt>`)
  } else {
    p('- Per-component do/don\'t, accessibility and tokens: `public/usage/<name>.md`.')
    p('- Live examples and props: the Storybook MCP server (`storybook` in `.mcp.json`; needs `npm run storybook`). Tools: `docs-list`, `docs-show`, `stories-find-by-component`, `stories-preview`, `test-run`.')
    p('- Registry search and install: the shadcn MCP server, namespace `@mantis` (needs `npm run dev` for the local registry).')
    p('- Visual intent and composition: `DESIGN.md`. Full token and component catalog: `public/llms.txt`.')
  }
  p()
  return L.join('\n')
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const out = renderAgents()
  writeFileSync(AGENTS_PATH, out)
  writeFileSync(CONSUMER_AGENTS_PATH, renderAgents({ consumer: true }))
  // DESIGN.md is hand-written; the hosted copy is what MANTIS.md links to.
  copyFileSync(join(root, 'DESIGN.md'), DESIGN_PUBLIC_PATH)
  console.log(`wrote AGENTS.md (${Buffer.byteLength(out)} bytes), registry/MANTIS.md and public/design.md`)
}
