// Rebuilds usage/index.mjs from the guides on disk, alphabetically. Shared by
// register-component.mjs and register-block.mjs.
import { readdirSync, writeFileSync } from 'node:fs'

export function writeUsageIndex() {
  const camel = (slug) => slug.replace(/-(\w)/g, (_, c) => c.toUpperCase()) + 'Usage'
  const slugs = readdirSync('usage').filter((f) => f.endsWith('.usage.mjs')).map((f) => f.replace('.usage.mjs', '')).sort()
  writeFileSync('usage/index.mjs', [
    '// Every usage guide, in alphabetical order. Regenerated by',
    '// scripts/register-component.mjs; scripts/usage-coverage.test.mjs fails if a',
    '// usage/*.usage.mjs file on disk is missing from this list.',
    ...slugs.map((slug) => `import { usage as ${camel(slug)} } from './${slug}.usage.mjs'`),
    '',
    `export const ALL_USAGE = [${slugs.map(camel).join(', ')}]`,
    '',
  ].join('\n'))
}
